jobs:
  - name: build-tasmota-builder
    plan:
      - get: platformio-release
        trigger: true
        params: { include_source_tarball: false }
      - load_var: platformio-version
        file: platformio-release/version
      - in_parallel:
        - get: lib
          trigger: false
        - get: oci-task-image
        - get: tasmota-builder-image-source
          trigger: true
      - task: build-image
        privileged: true
        file: lib/tasks/oci/build-image.yml
        image: oci-task-image
        input_mapping: { source: tasmota-builder-image-source }
        params:
          CONTEXT: source/images/tasmota-builder
          BUILD_ARG_PLATFORM_IO_VERSION: ((.:platformio-version))
        output_mapping: { image: image }
      - load_var: image-source-version
        file: tasmota-builder-image-source/.git/describe_ref # populated by the git-resource
      - put: tasmota-builder-image
        params:
          image: image/image.tar
          version: ((.:image-source-version))
          bump_aliases: true
  - name: build-jo
    plan:
      - get: jo-release
        trigger: true
        params: { include_source_tarball: true }
      - load_var: jo-version
        file: jo-release/version
      - in_parallel:
        - get: lib
          trigger: false
        - get: oci-task-image
      - task: untar-source
        file: lib/tasks/untar.yml
        input_mapping: { release: jo-release }
        output_mapping: { extracted: jo-source }
        params: { tarball: source.tar.gz }
      - get: alpine-image
      - task: canonicalize-source
        image: alpine-image
        config:
          platform: linux
          inputs: [ name: jo-source ]
          outputs: [ name: jo-source ]
          run:
            path: sh
            args:
              - -c
              - |
                mv jo-source/jpmens-jo-* jo-source/jpmens-jo
      - task: build-image
        privileged: true
        file: lib/tasks/oci/build-image.yml
        image: oci-task-image
        input_mapping: { source: jo-source }
        params: { CONTEXT: source/jpmens-jo }
        output_mapping: { image: image }
      - put: jo-image
        params:
          image: image/image.tar
          version: ((.:jo-version))
          bump_aliases: true
  - name: build-release
    plan:
      - in_parallel:
        - get: tasmota-release
          trigger: true
          params: { include_source_tarball: true }
        - get: lib
      - task: untar-tasmota-source
        file: lib/tasks/untar.yml
        input_mapping: { release: tasmota-release }
        output_mapping: { extracted: tasmota-source }
        params: { tarball: source.tar.gz }
      - get: tasmota-builder-image
# TODO Build across a map of name => []buildFlag, e.g.
# {
#   minimal: [ FIRMWARE_MINIMAL ],
#   prometheus: [ USE_PROMETHEUS ],
# }
      - in_parallel:
        - do:
          - task: build-minimal
            image: tasmota-builder-image
            config:
              platform: linux
              inputs: [ name: tasmota-source ]
              params:
                PLATFORMIO_CORE_DIR: pio-core
                PLATFORMIO_BUILD_FLAGS: -DFIRMWARE_MINIMAL
              caches: [ path: pio-core ]
              outputs: [ name: firmware-minimal ]
              run:
                path: sh
                args:
                  - -c
                  - |
                    PLATFORMIO_CORE_DIR=$(readlink -f "$PLATFORMIO_CORE_DIR")
                    echo Now we have "$(pio --version)" with core_dir of size "$(du -hs $PLATFORMIO_CORE_DIR)"
                    pio run --environment tasmota --project-dir tasmota-source/arendst-Tasmota-*/
                    cp tasmota-source/arendst-Tasmota-*/.pio/build/tasmota/firmware.bin firmware-minimal
                    gzip -9 firmware-minimal/firmware.bin
          - put: firmware-minimal
            params:
              file: firmware-minimal/firmware.bin.gz
              acl: public-read # https://stackoverflow.com/a/74522101/1044029 and https://github.com/concourse/s3-resource?tab=readme-ov-file#plan
        - do:
          - task: build-prometheus
            image: tasmota-builder-image
            config:
              platform: linux
              inputs: [ name: tasmota-source ]
              params:
                PLATFORMIO_CORE_DIR: pio-core
                PLATFORMIO_BUILD_FLAGS: -DUSE_PROMETHEUS
              caches: [ path: pio-core ]
              outputs: [ name: firmware ]
              run:
                path: sh
                args:
                  - -c
                  - |
                    PLATFORMIO_CORE_DIR=$(readlink -f "$PLATFORMIO_CORE_DIR")
                    echo Now we have "$(pio --version)" with core_dir of size "$(du -hs $PLATFORMIO_CORE_DIR)"
                    pio run --environment tasmota --project-dir tasmota-source/arendst-Tasmota-*/
                    cp tasmota-source/arendst-Tasmota-*/.pio/build/tasmota/firmware.bin firmware
                    gzip -9 firmware/firmware.bin
          - put: firmware
            params:
              file: firmware/firmware.bin.gz
              acl: public-read # https://stackoverflow.com/a/74522101/1044029 and https://github.com/concourse/s3-resource?tab=readme-ov-file#plan
      - put: tasmota-builder-release
        params:
          name: tasmota-release/version
          # body: release-notes/commits-since-last-tag.txt
          tag: tasmota-release/tag
          globs:
            - firmware-minimal/tasmota-minimal.bin.gz
            - firmware/tasmota.bin.gz
      - get: jo-image
      - task: prepare-notification
        image: jo-image
        config:
          platform: linux
          inputs: [ name: tasmota-builder-release ]
          outputs: [ name: release-notification ]
          run:
            path: sh
            args:
              - -c
              - |
                jo \
                  topic=suhlig \
                  title="Tasmota Builder" \
                  message="The new Tasmota firmware build $(cat tasmota-builder-release/tag) is available." \
                  "actions[]=$(jo action=view label=Pipeline url='$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME')" \
                  "actions[]=$(jo action=view label=Release url=$(cat tasmota-builder-release/url))" \
                | tee release-notification/message.json
      - put: ntfy
        params: { file: release-notification/message.json }
resources:
  - name: lib
    type: git
    icon: file-tree
    source: &github
      uri: git@github.com:suhlig/concourse-task-library.git
      private_key: ((secrets.github.ssh_key))
  - name: tasmota-builder-image-source
    type: git
    icon: github
    source:
      <<: *github
      uri: git@github.com:uhlig-it/tasmota-builder.git
      paths: [ images/tasmota-builder/* ]
  - name: platformio-release
    type: github-release
    icon: package
    source: &github-release
      owner: platformio
      repository: platformio-core
      access_token: ((secrets.github.access_token))
      pre_release: false
  - name: tasmota-release
    type: github-release
    icon: package
    source:
      <<: *github-release
      owner: arendst
      repository: Tasmota
      pre_releases: false
  - name: tasmota-builder-image
    type: registry-image
    icon: docker
    source: &dockerhub
      repository: uhligit/tasmota-builder
      username: ((secrets.dockerhub.username))
      password: ((secrets.dockerhub.authtoken))
      pre_releases: false
      debug: false
      tag: latest
  - name: oci-task-image
    type: registry-image
    icon: docker
    source:
      <<: *dockerhub
      repository: concourse/oci-build-task
  - name: jo-image
    type: registry-image
    icon: docker
    source:
      <<: *dockerhub
      repository: uhligit/jo
  - name: alpine-image
    type: registry-image
    icon: docker
    source:
      <<: *dockerhub
      repository: alpine
  - name: firmware
    type: s3
    source: &s3
      bucket: uhlig-it-tasmota-builds
      versioned_file: tasmota.bin.gz
      access_key_id: ((secrets.b2.keyID))
      secret_access_key: ((secrets.b2.applicationKey))
      endpoint: s3.us-west-001.backblazeb2.com
  - name: firmware-minimal
    type: s3
    source:
      <<: *s3
      versioned_file: tasmota-minimal.bin.gz
  - name: tasmota-builder-release
    type: github-release
    icon: github-circle
    source:
      <<: *github-release
      owner: uhlig-it
      repository: tasmota-builder # concourse-uhlig-it must have write access
      pre_release: false
      drafts: false
  - name: jo-release
    type: github-release
    icon: github-circle
    source:
      <<: *github-release
      owner: jpmens
      repository: jo
      pre_release: false
      drafts: false
  - name: ntfy
    type: http-resource
    source:
      url: https://ntfy.sh
      build_metadata: [ body ]
      out_only: true
resource_types:
  - name: http-resource
    type: docker-image
    source: { repository: jgriff/http-resource }
